### ISSUE TITLE
Add support to new shipping platform.

### ISSUE THREAD

**Issue by TomasAndersonFang** [DFY-NCSU/slash-phase6#19]
I create this issue report to add support to new online shopping platforms, such as Amazon or Costco.

**Comment by TheFatBlue** [comment]
Is there any progress for this? I'm super excited about this function!!!! 😍

**Comment by TomasAndersonFang** [comment]
> Is there any progress for this? I'm super excited about this function!!!! 😍

@TheFatBlue I now finished local implementation for Costco and successfully tested it. I tried to finish it as soon as possible :hamster:

**Comment by TomasAndersonFang** [comment]
@TheFatBlue I already submitted PR #28 for supporting the Costco platform. Please review and ensure it's good for merging :)
