### ISSUE TITLE
We need to fix the logic of `check_price` and make it general to all tests.

### ISSUE THREAD

**Issue by TomasAndersonFang** [DFY-NCSU/slash-phase6#22]
I created this issue report to keep trace of the bug in `check_price` function. I initially implemented this function for test Walmart and eBay APIs, but now @TheFatBlue found this function cannot be applied to new tests, such as [test_feature.py](https://github.com/DFY-NCSU/slash-phase5/blob/dev/tests/test_feature.py). We plan to fix this bug when we finish all tests.

**Comment by TheFatBlue** [comment]
Solved in #41 . Close
